enableTransparentWorkspaces: false

nodeLinker: node-modules

# npmRegistryServer: "http://192.168.1.152:8081/repository/npm"
npmRegistryServer: "https://registry.npmjs.org/"

unsafeHttpWhitelist:
  - 192.168.1.152
